{
  "name": "gulp-starter",
  "version": "2.0.0",
  "description": "Gulp starter with common tasks and scenarios",
  "dependencies": {
  },
  "devDependencies": {
    "browser-sync": "^2.8.0",
    "del": "^2.0.0",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^2.3.1",
    "gulp-changed": "^1.2.1",
    "gulp-concat": "^2.6.0",
    "gulp-csso": "^1.0.0",
    "gulp-filesize": "^0.0.6",
    "gulp-filter": "^3.0.1",
    "gulp-gh-pages": "^0.5.2",
    "gulp-htmlmin": "^1.1.3",
    "gulp-iconfont": "^4.0.1",
    "gulp-if": "^1.2.5",
    "gulp-imagemin": "^2.3.0",
    "gulp-inject": "^1.3.1",
    "gulp-jscs": "^2.0.0",
    "gulp-jshint": "^1.11.2",
    "gulp-minify-css": "^1.2.0",
    "gulp-notify": "^2.2.0",
    "gulp-nunjucks-render": "^0.2.1",
    "gulp-plumber": "^1.0.1",
    "gulp-print": "^1.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-rev": "^6.0.1",
    "gulp-rev-replace": "^0.4.2",
    "gulp-sass": "^2.0.4",
    "gulp-sequence": "^0.4.0",
    "gulp-sizereport": "^1.1.2",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-svgstore": "^5.0.3",
    "gulp-task-listing": "^1.0.1",
    "gulp-uglify": "^1.2.0",
    "gulp-useref": "^1.2.0",
    "gulp-util": "^3.0.6",
    "gulp-watch": "^4.3.3",
    "open": "^0.0.5",
    "require-dir": "^0.3.0",
    "run-sequence": "^1.1.2",
    "wiredep": "^3.0.0-beta",
    "yargs": "^3.15.0"
  }
} 
